/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.RedeSocial;

public abstract class Influencer {
    String name;
    int seguidores;
    
    public Influencer(String name, int seguidores){
        this.name = name;
        this.seguidores = seguidores;
    }
    public void exibirInfo(){
        System.out.println("Nome:" + name +", Seguidores: "+ seguidores);
    }
    
    public abstract void postarConteudo();
    public abstract void interagir();
}

